version: '2'
services:
    smartlvopersw-app:
        image: smartlvopersw
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://smartlvopersw-mariadb:3306/smartlvopersw
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    smartlvopersw-mariadb:
        extends:
            file: mariadb.yml
            service: smartlvopersw-mariadb
